# Clock

set_property PACKAGE_PIN W5 [get_ports sys_clock]
set_property IOSTANDARD LVCMOS33 [get_ports sys_clock]
create_clock -period 10.000 -name sys_clk_pin -waveform {0.000 5.000} -add [get_ports sys_clock]

#VGA Connector
set_property PACKAGE_PIN G19 [get_ports {rgb_out[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_out[8]}]
set_property PACKAGE_PIN H19 [get_ports {rgb_out[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_out[9]}]
set_property PACKAGE_PIN J19 [get_ports {rgb_out[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_out[10]}]
set_property PACKAGE_PIN N19 [get_ports {rgb_out[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_out[11]}]
set_property PACKAGE_PIN N18 [get_ports {rgb_out[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_out[0]}]
set_property PACKAGE_PIN L18 [get_ports {rgb_out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_out[1]}]
set_property PACKAGE_PIN K18 [get_ports {rgb_out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_out[2]}]
set_property PACKAGE_PIN J18 [get_ports {rgb_out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_out[3]}]
set_property PACKAGE_PIN J17 [get_ports {rgb_out[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_out[4]}]
set_property PACKAGE_PIN H17 [get_ports {rgb_out[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_out[5]}]
set_property PACKAGE_PIN G17 [get_ports {rgb_out[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_out[6]}]
set_property PACKAGE_PIN D17 [get_ports {rgb_out[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_out[7]}]
set_property PACKAGE_PIN P19 [get_ports hsync]
set_property IOSTANDARD LVCMOS33 [get_ports hsync]
set_property PACKAGE_PIN R19 [get_ports vsync]
set_property IOSTANDARD LVCMOS33 [get_ports vsync]

set_property PACKAGE_PIN U18 [get_ports Reset]
set_property IOSTANDARD LVCMOS33 [get_ports Reset]

##Pmod Header JB
##Sch name = JB1
set_property PACKAGE_PIN A14 [get_ports cs]
set_property IOSTANDARD LVCMOS33 [get_ports cs]
#Sch name = JB2
set_property PACKAGE_PIN A16 [get_ports mosi_out]
set_property IOSTANDARD LVCMOS33 [get_ports mosi_out]
#Sch name = JB3
set_property PACKAGE_PIN B15 [get_ports clk_spi]
set_property IOSTANDARD LVCMOS33 [get_ports clk_spi]
#Sch name = JB4
set_property PACKAGE_PIN B16 [get_ports miso_in]
set_property IOSTANDARD LVCMOS33 [get_ports miso_in]

create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list design_1_i/clk_wiz_0/inst/clk_out2]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 1 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list design_1_i/axi_quad_spi_0_io0_o]]
create_debug_core u_ila_1 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_1]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_1]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_1]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_1]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_1]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_1]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_1]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_1]
set_property port_width 1 [get_debug_ports u_ila_1/clk]
connect_debug_port u_ila_1/clk [get_nets [list design_1_i/clk_wiz_0/inst/clk_out1]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe0]
set_property port_width 1 [get_debug_ports u_ila_1/probe0]
connect_debug_port u_ila_1/probe0 [get_nets [list design_1_i/clk_wiz_0_clk_out2]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 1 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list design_1_i/axi_quad_spi_0_ss_t]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 1 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list design_1_i/io1_i_1]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets u_ila_1_clk_out1]
