webtalk_init -webtalk_dir C:\\Users\\khem_\\Desktop\\DIG_DESIGN_LAB\\final_project\\microblaze_vga\\microblaze_vga.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2017-05-06 01:21:05" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2016.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2016.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211291456_0_0_754" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "amcrklnbappus5kpu3l7f3hsai" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2016.4_6" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "6" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-4690 CPU @ 3.50GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3500 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1494008259088" -context "sdk\\\\bsp/1494008259088"
webtalk_add_data -client sdk -key hwid -value "1494007635850" -context "sdk\\\\bsp/1494008259088"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1494008259088"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\bsp/1494008259088"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1494008259088"
webtalk_add_data -client sdk -key uid -value "1494008260223" -context "sdk\\\\application/1494008260223"
webtalk_add_data -client sdk -key hwid -value "1494007635850" -context "sdk\\\\application/1494008260223"
webtalk_add_data -client sdk -key bspid -value "1494008259088" -context "sdk\\\\application/1494008260223"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1494008260223"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1494008260223"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\application/1494008260223"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1494008260223"
webtalk_add_data -client sdk -key LangUsed -value "C" -context "sdk\\\\application/1494008260223"
webtalk_add_data -client sdk -key Procused -value "microblaze" -context "sdk\\\\application/1494008260223"
webtalk_add_data -client sdk -key projSize -value "84.923828125" -context "sdk\\\\application/1494008260223"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1494008465234"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1494008465234"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1494008465234"
webtalk_add_data -client sdk -key DebugCount -value "2" -context "sdk\\\\bsp/1494008465234"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1494008465234"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1494008465234"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1494008465234"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1494008465234"
webtalk_transmit -clientid 2108328785 -regid "211291456_0_0_754" -xml C:\\Users\\khem_\\Desktop\\DIG_DESIGN_LAB\\final_project\\microblaze_vga\\microblaze_vga.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html C:\\Users\\khem_\\Desktop\\DIG_DESIGN_LAB\\final_project\\microblaze_vga\\microblaze_vga.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm C:\\Users\\khem_\\Desktop\\DIG_DESIGN_LAB\\final_project\\microblaze_vga\\microblaze_vga.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
